language: smalltalk
sudo: false
os:
- linux
smalltalk:
- Pharo64-8.0
- Pharo64-7.0
- Pharo32-7.0
- Pharo32-6.1
matrix:
  allow_failures:
  - smalltalk: Pharo64-8.0
  fast_finish: true
before_deploy:
  - cp "${SMALLTALK_CI_IMAGE}" "Willow-SpinKit.image"
  - cp "${SMALLTALK_CI_CHANGES}" "Willow-SpinKit.changes"
  - zip -q "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip" "Willow-SpinKit.image" "Willow-SpinKit.changes"
deploy:
  provider: releases
  api_key:
    secure: FvsvhTOX4tSrCgIhctH2A3OXZj0ke+c0tcAk40ZrNFq+oGA+HtFoyYL2zKUvcMF0TqawjXQqIBy9HoS4lhVhZqKIIKrUAmq4qEaQZid4i8CH+aJSeqMioXt5ePcWISUSjcWWDwY3d5pV+TvuT/uP0AosPQjVewfaWMAu8s+cs/CWKRYJZFExA+BKG1bcl4xgtKNn4L9z073Hvs8MzFRjohqah4UagAxcSrzk7BQ9PS+/4kIda8iEpbceFPV/xnv1vpEUQWd90ocdsEuAJifyCXmaFYc+ZO1uPbWWAqb6mVLH6s1ze4/AXCPgUQxtPxneCtX+U1GexAS/TvJ+zpHekrxCe59S59OgTPYpaSBL73pP65gIot2SjojpdnbSl1dPDZmUjGQeVo6T21GhAX59Viqailf1sQCnK9THxa8urw0QbC98TDSAMTGTxZVpFhfG5xcb6ABDQ0wF2XIpxLYf9SEaHeEEHfM7JYrilkLmYteJIe2XoOvSLujTQquxfcmREClRUBCS9xD/BXcNol+VcjEn3afIDyRZHWUoljQ7Z5KsTUqppI+L5vbUYDjO5S7YmBUaQYes5UkGgGV2XquqKuNbPopp1a/lkrsn+JCT3jOY2LZE+aISF793qNaGcB2IHQSg2Y6XgPmGmBR53+32ajED9lURCPOEWYPoTZvHNwg=
  file: "${TRAVIS_BRANCH}-${TRAVIS_SMALLTALK_VERSION}.zip"
  skip_cleanup: true
  on:
    repo: ba-st/Willow-SpinKit
    tags: true
