Extension { #name : #ComponentClassificationCommandBuilder }

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> bounce [

	^ self commandStyledWith: #bounce
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> bounceDot [

	^ self commandStyledWith: #bounceDot
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> chase [

	^ self commandStyledWith: #chase
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> chaseDot [

	^ self commandStyledWith: #chaseDot
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> circle [

	^ self commandStyledWith: #circle
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> circleDot [

	^ self commandStyledWith: #circleDot
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> circleFade [

	^ self commandStyledWith: #circleFade
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> circleFadeDot [

	^ self commandStyledWith: #circleFadeDot
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> flow [

	^ self commandStyledWith: #flow
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> flowDot [

	^ self commandStyledWith: #flowDot
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> fold [

	^ self commandStyledWith: #fold
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> foldCube [

	^ self commandStyledWith: #foldCube
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> grid [

	^ self commandStyledWith: #grid
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> gridCube [

	^ self commandStyledWith: #gridCube
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> plane [

	^ self commandStyledWith: #plane
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> pulse [

	^ self commandStyledWith: #pulse
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> spinKit [

	classificationNamespace := classificationNamespace >> #spinKit
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> swing [

	^ self commandStyledWith: #swing
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> swingDot [

	^ self commandStyledWith: #swingDot
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> wander [

	^ self commandStyledWith: #wander
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> wanderCube [

	^ self commandStyledWith: #wanderCube
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> wave [

	^ self commandStyledWith: #wave
]

{ #category : #'*Willow-SpinKit' }
ComponentClassificationCommandBuilder >> waveRectangle [

	^ self commandStyledWith: #waveRectangle
]
